apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-test
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-pv-test-unique-id
    volumeAttributes:
      server: truenas.local
      share: /mnt/tank/k3s-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-pv-test
  storageClassName: ""
