# verbose = "info"
no_progress = true
include_mail = false
max_concurrency = 6
retry_wait_time = 2
timeout = 20
root_dir = "docs"

accept = ["200", "206", "301", "302", "303", "307", "308", "401", "403", "429"]

exclude = [
  "URL$",
  "^/new-sources/",
  "/new-sources/",
  "docs/new-sources/",
  "^http://127\\.0\\.0\\.1",
  "^http://localhost",
  "^https://127\\.0\\.0\\.1",
  "^https://chat\\.lmsys\\.org/",
  "^https://docs\\.browser-use\\.ai/",
  "^https://github\\.com/AbanteAI/mentat",
  "^https://github\\.com/allenai/ARC-benchmark",
  "^https://github\\.com/anthropic/claude-code",
  "^https://github\\.com/chiahsuan/ASDiv",
  "^https://github\\.com/clihub/clihub",
  "^https://github\\.com/clusterfudge/paperless-ai",
  "^https://github\\.com/google-jules/anti-gravity",
  "^https://github\\.com/gpt-engineer-ai/gpt-engineer",
  "^https://github\\.com/marwanjeridi/ollama-benchmark",
  "^https://github\\.com/pro-puffin/terminal-bench",
  "^https://github\\.com/the-omni-tools/omni-tools",
  "^https://huggingface\\.co/tasks/",
  "^https://humanityslastexam\\.ai/",
  "^https://localhost",
  "^https://openrouter\\.ai/",
  "^https://superconductor\\.ai/",
  "^https://vercel\\.com/blog/tag/ai",
  "^https://www\\.apple\\.com/silicon/",
  "^https://www\\.cognition-labs\\.com/devin",
  "^https://arena\\.lmsys\\.org/",
  "docs/templates/URL",
  "docs/templates/relative-link\\.md",
  "https://chat.lmsys.org/",
  "https://chatgpt\\.com/share/",
  "https://docs.browser-use.ai/",
  "https://github\\.com/TomW1605/kitchenowl.*",
  "https://github\\.com/phidata-hq/phidata.*",
  "https://huggingface.co/tasks/natural-language-inference",
  "https://humanityslastexam.ai/",
  "https://ollama.com/docs/api",
  "https://openrouter.ai/docs/guides/community/live-kit",
  "https://openrouter.ai/docs/overview/introduction",
  "https://openrouter\\.ai/docs/guides/community/live-kit",
  "https://squidfox.dev/mkdocs-material/",
  "https://squidfox\\.dev/mkdocs-material/",
  "https://superconductor.ai/",
  "https://vercel.com/blog/tag/ai",
  "https://www.apple.com/silicon/",
  "https://www.cognition-labs.com/devin",
  "https://www.voyageai.com/pricing",
  "https://github.com/democratize-technology/.*",
  "relative-link\\.md",
]
