#!/usr/bin/env bash
# install_gh_dry_run_shim.sh — make every later step's `gh` read-only.
#
# Usage (in a workflow step, after actions/checkout):
#   - if: env.DRY_RUN == 'true'
#     run: bash scripts/ci/install_gh_dry_run_shim.sh
#
# Why: the automation lanes write through `gh` from many places (inline bash,
# Python scripts calling subprocess). Rather than threading a --dry-run flag
# through every script, this installs a `gh` wrapper first on $GITHUB_PATH for
# the rest of the job. Read calls (list/view/api GET) pass through to the real
# gh, so the lane exercises its real queries; mutating calls are printed as
# "[dry-run] gh ..." and report success without touching the repository.
#
# Mutating = issue/pr/label writes, workflow run, run rerun/cancel, release,
# secret/variable writes, and `gh api` with a non-GET method or any request
# fields (gh api defaults to POST when -f/-F/--input is given).
#
# git pushes are not covered — lanes guard those (create-pull-request steps)
# with their own `!dry_run` condition.
set -euo pipefail

real_gh="$(command -v gh)"
shim_dir="${RUNNER_TEMP:-/tmp}/gh-dry-run-shim"
mkdir -p "$shim_dir"

cat > "$shim_dir/gh" <<EOF
#!/usr/bin/env bash
# Generated by scripts/ci/install_gh_dry_run_shim.sh — dry-run gh wrapper.
REAL_GH="$real_gh"
EOF

cat >> "$shim_dir/gh" <<'EOF'
say() { printf '[dry-run] would run: gh %s\n' "$*" >&2; }

case "${1:-} ${2:-}" in
  "issue create"|"issue edit"|"issue comment"|"issue close"|"issue reopen"|"issue delete"|\
  "issue lock"|"issue unlock"|"issue pin"|"issue unpin"|"issue transfer"|\
  "pr create"|"pr edit"|"pr comment"|"pr close"|"pr reopen"|"pr merge"|"pr ready"|"pr review"|\
  "label create"|"label edit"|"label delete"|"label clone"|\
  "workflow run"|"workflow enable"|"workflow disable"|\
  "run rerun"|"run cancel"|"run delete"|\
  "release create"|"release edit"|"release delete"|"release upload"|\
  "secret set"|"secret delete"|"variable set"|"variable delete"|\
  "cache delete"|"repo edit"|"repo delete")
    say "$@"
    exit 0
    ;;
esac

if [ "${1:-}" = "api" ]; then
  method="" has_fields=0 prev=""
  for arg in "$@"; do
    case "$prev" in
      -X|--method) method="$arg" ;;
    esac
    case "$arg" in
      -X?*) method="${arg#-X}" ;;
      --method=*) method="${arg#--method=}" ;;
      -f|-F|--field|--raw-field|--input|-f?*|-F?*|--field=*|--raw-field=*|--input=*) has_fields=1 ;;
    esac
    prev="$arg"
  done
  method="$(printf '%s' "$method" | tr '[:lower:]' '[:upper:]')"
  # A GraphQL query with fields is a read unless it is a mutation.
  if [ "${2:-}" = "graphql" ]; then
    if printf '%s\n' "$@" | grep -qiE '(^|[^a-z])mutation([^a-z]|$)'; then
      say "$@"; echo '{}'; exit 0
    fi
    exec "$REAL_GH" "$@"
  fi
  if { [ -n "$method" ] && [ "$method" != "GET" ] && [ "$method" != "HEAD" ]; } ||
     { [ -z "$method" ] && [ "$has_fields" = "1" ]; }; then
    say "$@"
    echo '{}'
    exit 0
  fi
fi

exec "$REAL_GH" "$@"
EOF

chmod +x "$shim_dir/gh"
if [ -n "${GITHUB_PATH:-}" ]; then
  echo "$shim_dir" >> "$GITHUB_PATH"
fi
echo "Dry-run: mutating gh calls are intercepted for the rest of this job ($shim_dir/gh -> $real_gh)."
